name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH and Deploy to DigitalOcean
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: 64.225.102.81
      run: |
        # Setup SSH Key
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Disable SSH Host Key Checking
        echo "$SSH_HOST ssh-ed25519 ..." >> ~/.ssh/known_hosts
        
        # Copy deploy script to the server
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./scripts/deploy.sh root@$SSH_HOST:/tmp/deploy.sh
        
        # Execute deploy script on the server
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@$SSH_HOST 'bash /tmp/deploy.sh'

