name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: 64.225.102.81
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          /home/user/deploy.sh